# Generated by Django 3.0 on 2021-08-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210806_0406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
